/*
 * generated by Xtext 2.10.0
 */
package org.cirad.dsl.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BreactiveStandaloneSetup extends BreactiveStandaloneSetupGenerated {

	def static void doSetup() {
		new BreactiveStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
