/*
 * generated by Xtext
 */
package org.cirad.dsl.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BehaviordslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.cirad.dsl.xtext.ui.internal.BehaviordslActivator.getInstance().getInjector("org.cirad.dsl.xtext.Behaviordsl");
	}
	
}
