/*
 * generated by Xtext
 */
package org.cirad.dsl.ecec.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EcecRuntimeModule extends org.cirad.dsl.ecec.xtext.AbstractEcecRuntimeModule {

}
