/*
 * generated by Xtext 2.10.0
 */
package org.cirad.dsl.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BreactiveAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/cirad/dsl/xtext/parser/antlr/internal/InternalBreactive.tokens");
	}
}
