/*
 * generated by Xtext 2.10.0
 */
package org.cirad.dsl.xtext.parser.antlr;

import com.google.inject.Inject;
import org.cirad.dsl.xtext.parser.antlr.internal.InternalBreactiveParser;
import org.cirad.dsl.xtext.services.BreactiveGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BreactiveParser extends AbstractAntlrParser {

	@Inject
	private BreactiveGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBreactiveParser createParser(XtextTokenStream stream) {
		return new InternalBreactiveParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public BreactiveGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BreactiveGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
