/*
 * generated by Xtext
 */
package org.cirad.dsl.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BehaviordslStandaloneSetup extends BehaviordslStandaloneSetupGenerated{

	public static void doSetup() {
		new BehaviordslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

