/*
 * generated by Xtext
 */
package org.cirad.dsl.xtext;

//import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BehaviordslRuntimeModule extends org.cirad.dsl.xtext.AbstractBehaviordslRuntimeModule {
	
	 //@Override
	 //   public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
	 //       return BehaviorDSLQNP.class;
	 //   }

}
