/*
 * generated by Xtext
 */
package org.cirad.dsl.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BehaviordslUiModule extends org.cirad.dsl.xtext.ui.AbstractBehaviordslUiModule {
	public BehaviordslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
