/*
 * generated by Xtext
 */
package org.cirad.dsl.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.cirad.dsl.xtext.ui.internal.BehaviordslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BehaviordslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BehaviordslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BehaviordslActivator.getInstance().getInjector(BehaviordslActivator.ORG_CIRAD_DSL_XTEXT_BEHAVIORDSL);
	}
	
}
