/*
 * generated by Xtext 2.10.0
 */
package org.cirad.dsl.xtext.ui.tests;

import com.google.inject.Injector;
import org.cirad.dsl.xtext.breactive.ui.internal.BreactiveActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class BreactiveUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BreactiveActivator.getInstance().getInjector("org.cirad.dsl.xtext.Breactive");
	}

}
