/*
 * generated by Xtext
 */
package org.cirad.dsl.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BehaviordslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/cirad/dsl/xtext/parser/antlr/internal/InternalBehaviordsl.tokens");
	}
}
