/*
 * generated by Xtext
 */
package org.cirad.dsl.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.cirad.dsl.xtext.services.BehaviordslGrammarAccess;

public class BehaviordslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BehaviordslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.cirad.dsl.xtext.parser.antlr.internal.InternalBehaviordslParser createParser(XtextTokenStream stream) {
		return new org.cirad.dsl.xtext.parser.antlr.internal.InternalBehaviordslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public BehaviordslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BehaviordslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
