/*
 * generated by Xtext
 */
package org.cirad.dsl.ecec.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractEcecValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.cirad.dsl.ecec.xtext.ecec.EcecPackage.eINSTANCE);
		return result;
	}
}
