/**
 * generated by Xtext
 */
package org.cirad.dsl.ecec.xtext.validation;

import org.cirad.dsl.ecec.xtext.validation.AbstractEcecValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class EcecValidator extends AbstractEcecValidator {
}
