/*
 * generated by Xtext 2.10.0
 */
package org.cirad.dsl.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBreactiveScopeProvider extends DelegatingScopeProvider {
}
