/*
 * generated by Xtext 2.10.0
 */
package org.cirad.dsl.xtext.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class BreactiveScopeProvider extends AbstractBreactiveScopeProvider {

}
