/*
 * generated by Xtext 2.10.0
 */
package org.cirad.dsl.xtext.ui;

import com.google.inject.Injector;
import org.cirad.dsl.xtext.breactive.ui.internal.BreactiveActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BreactiveExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BreactiveActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BreactiveActivator.getInstance().getInjector(BreactiveActivator.ORG_CIRAD_DSL_XTEXT_BREACTIVE);
	}
	
}
